version: '3.3'

services:
  yorkie:
    image: 'krapi0314/yorkie:test'
    container_name: 'yorkie'
    command: ['server', '--enable-pprof']
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
