//
// Copyright 2022 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=js+dts,js_import_style=legacy_commonjs"
// @generated from file src/api/yorkie/v1/admin.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { CreateProjectRequest, CreateProjectResponse, GetDocumentRequest, GetDocumentResponse, GetProjectRequest, GetProjectResponse, GetSnapshotMetaRequest, GetSnapshotMetaResponse, ListChangesRequest, ListChangesResponse, ListDocumentsRequest, ListDocumentsResponse, ListProjectsRequest, ListProjectsResponse, LogInRequest, LogInResponse, RemoveDocumentByAdminRequest, RemoveDocumentByAdminResponse, SearchDocumentsRequest, SearchDocumentsResponse, SignUpRequest, SignUpResponse, UpdateProjectRequest, UpdateProjectResponse } = require("./admin_pb.js");
const { MethodKind } = require("@bufbuild/protobuf");

/**
 * Admin is a service that provides a API for Admin.
 *
 * @generated from service yorkie.v1.AdminService
 */
const AdminService = {
  typeName: "yorkie.v1.AdminService",
  methods: {
    /**
     * @generated from rpc yorkie.v1.AdminService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: SignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.LogIn
     */
    logIn: {
      name: "LogIn",
      I: LogInRequest,
      O: LogInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: CreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListProjects
     */
    listProjects: {
      name: "ListProjects",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetProject
     */
    getProject: {
      name: "GetProject",
      I: GetProjectRequest,
      O: GetProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.UpdateProject
     */
    updateProject: {
      name: "UpdateProject",
      I: UpdateProjectRequest,
      O: UpdateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListDocuments
     */
    listDocuments: {
      name: "ListDocuments",
      I: ListDocumentsRequest,
      O: ListDocumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetDocument
     */
    getDocument: {
      name: "GetDocument",
      I: GetDocumentRequest,
      O: GetDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.RemoveDocumentByAdmin
     */
    removeDocumentByAdmin: {
      name: "RemoveDocumentByAdmin",
      I: RemoveDocumentByAdminRequest,
      O: RemoveDocumentByAdminResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetSnapshotMeta
     */
    getSnapshotMeta: {
      name: "GetSnapshotMeta",
      I: GetSnapshotMetaRequest,
      O: GetSnapshotMetaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.SearchDocuments
     */
    searchDocuments: {
      name: "SearchDocuments",
      I: SearchDocumentsRequest,
      O: SearchDocumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListChanges
     */
    listChanges: {
      name: "ListChanges",
      I: ListChangesRequest,
      O: ListChangesResponse,
      kind: MethodKind.Unary,
    },
  }
};


exports.AdminService = AdminService;
