//
// Copyright 2022 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts,js_import_style=module"
// @generated from file src/api/yorkie/v1/admin.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Change, DocumentSummary, Project, UpdatableProjectFields, User } from "./resources_pb.js";

/**
 * @generated from message yorkie.v1.SignUpRequest
 */
export const SignUpRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.SignUpRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.SignUpResponse
 */
export const SignUpResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.SignUpResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
  ],
);

/**
 * @generated from message yorkie.v1.LogInRequest
 */
export const LogInRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.LogInRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.LogInResponse
 */
export const LogInResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.LogInResponse",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.CreateProjectRequest
 */
export const CreateProjectRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.CreateProjectRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.CreateProjectResponse
 */
export const CreateProjectResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.CreateProjectResponse",
  () => [
    { no: 1, name: "project", kind: "message", T: Project },
  ],
);

/**
 * @generated from message yorkie.v1.GetProjectRequest
 */
export const GetProjectRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.GetProjectRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.GetProjectResponse
 */
export const GetProjectResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.GetProjectResponse",
  () => [
    { no: 1, name: "project", kind: "message", T: Project },
  ],
);

/**
 * @generated from message yorkie.v1.ListProjectsRequest
 */
export const ListProjectsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ListProjectsRequest",
  [],
);

/**
 * @generated from message yorkie.v1.ListProjectsResponse
 */
export const ListProjectsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ListProjectsResponse",
  () => [
    { no: 1, name: "projects", kind: "message", T: Project, repeated: true },
  ],
);

/**
 * @generated from message yorkie.v1.UpdateProjectRequest
 */
export const UpdateProjectRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.UpdateProjectRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "fields", kind: "message", T: UpdatableProjectFields },
  ],
);

/**
 * @generated from message yorkie.v1.UpdateProjectResponse
 */
export const UpdateProjectResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.UpdateProjectResponse",
  () => [
    { no: 1, name: "project", kind: "message", T: Project },
  ],
);

/**
 * @generated from message yorkie.v1.ListDocumentsRequest
 */
export const ListDocumentsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ListDocumentsRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "previous_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "is_forward", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "include_snapshot", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.ListDocumentsResponse
 */
export const ListDocumentsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ListDocumentsResponse",
  () => [
    { no: 1, name: "documents", kind: "message", T: DocumentSummary, repeated: true },
  ],
);

/**
 * @generated from message yorkie.v1.GetDocumentRequest
 */
export const GetDocumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.GetDocumentRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.GetDocumentResponse
 */
export const GetDocumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.GetDocumentResponse",
  () => [
    { no: 1, name: "document", kind: "message", T: DocumentSummary },
  ],
);

/**
 * @generated from message yorkie.v1.RemoveDocumentByAdminRequest
 */
export const RemoveDocumentByAdminRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.RemoveDocumentByAdminRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "force", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.RemoveDocumentByAdminResponse
 */
export const RemoveDocumentByAdminResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.RemoveDocumentByAdminResponse",
  [],
);

/**
 * @generated from message yorkie.v1.GetSnapshotMetaRequest
 */
export const GetSnapshotMetaRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.GetSnapshotMetaRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "server_seq", kind: "scalar", T: 3 /* ScalarType.INT64 */, L: 1 /* LongType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.GetSnapshotMetaResponse
 */
export const GetSnapshotMetaResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.GetSnapshotMetaResponse",
  () => [
    { no: 1, name: "snapshot", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "lamport", kind: "scalar", T: 3 /* ScalarType.INT64 */, L: 1 /* LongType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.SearchDocumentsRequest
 */
export const SearchDocumentsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.SearchDocumentsRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message yorkie.v1.SearchDocumentsResponse
 */
export const SearchDocumentsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.SearchDocumentsResponse",
  () => [
    { no: 1, name: "total_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "documents", kind: "message", T: DocumentSummary, repeated: true },
  ],
);

/**
 * @generated from message yorkie.v1.ListChangesRequest
 */
export const ListChangesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ListChangesRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "previous_seq", kind: "scalar", T: 3 /* ScalarType.INT64 */, L: 1 /* LongType.STRING */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "is_forward", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.ListChangesResponse
 */
export const ListChangesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "yorkie.v1.ListChangesResponse",
  () => [
    { no: 1, name: "changes", kind: "message", T: Change, repeated: true },
  ],
);

