//
// Copyright 2022 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=js+dts,js_import_style=module"
// @generated from file src/api/yorkie/v1/admin.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProjectRequest, CreateProjectResponse, GetDocumentRequest, GetDocumentResponse, GetProjectRequest, GetProjectResponse, GetSnapshotMetaRequest, GetSnapshotMetaResponse, ListChangesRequest, ListChangesResponse, ListDocumentsRequest, ListDocumentsResponse, ListProjectsRequest, ListProjectsResponse, LogInRequest, LogInResponse, RemoveDocumentByAdminRequest, RemoveDocumentByAdminResponse, SearchDocumentsRequest, SearchDocumentsResponse, SignUpRequest, SignUpResponse, UpdateProjectRequest, UpdateProjectResponse } from "./admin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Admin is a service that provides a API for Admin.
 *
 * @generated from service yorkie.v1.AdminService
 */
export declare const AdminService: {
  readonly typeName: "yorkie.v1.AdminService",
  readonly methods: {
    /**
     * @generated from rpc yorkie.v1.AdminService.SignUp
     */
    readonly signUp: {
      readonly name: "SignUp",
      readonly I: typeof SignUpRequest,
      readonly O: typeof SignUpResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.LogIn
     */
    readonly logIn: {
      readonly name: "LogIn",
      readonly I: typeof LogInRequest,
      readonly O: typeof LogInResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.CreateProject
     */
    readonly createProject: {
      readonly name: "CreateProject",
      readonly I: typeof CreateProjectRequest,
      readonly O: typeof CreateProjectResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListProjects
     */
    readonly listProjects: {
      readonly name: "ListProjects",
      readonly I: typeof ListProjectsRequest,
      readonly O: typeof ListProjectsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetProject
     */
    readonly getProject: {
      readonly name: "GetProject",
      readonly I: typeof GetProjectRequest,
      readonly O: typeof GetProjectResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.UpdateProject
     */
    readonly updateProject: {
      readonly name: "UpdateProject",
      readonly I: typeof UpdateProjectRequest,
      readonly O: typeof UpdateProjectResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListDocuments
     */
    readonly listDocuments: {
      readonly name: "ListDocuments",
      readonly I: typeof ListDocumentsRequest,
      readonly O: typeof ListDocumentsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetDocument
     */
    readonly getDocument: {
      readonly name: "GetDocument",
      readonly I: typeof GetDocumentRequest,
      readonly O: typeof GetDocumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.RemoveDocumentByAdmin
     */
    readonly removeDocumentByAdmin: {
      readonly name: "RemoveDocumentByAdmin",
      readonly I: typeof RemoveDocumentByAdminRequest,
      readonly O: typeof RemoveDocumentByAdminResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetSnapshotMeta
     */
    readonly getSnapshotMeta: {
      readonly name: "GetSnapshotMeta",
      readonly I: typeof GetSnapshotMetaRequest,
      readonly O: typeof GetSnapshotMetaResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.SearchDocuments
     */
    readonly searchDocuments: {
      readonly name: "SearchDocuments",
      readonly I: typeof SearchDocumentsRequest,
      readonly O: typeof SearchDocumentsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListChanges
     */
    readonly listChanges: {
      readonly name: "ListChanges",
      readonly I: typeof ListChangesRequest,
      readonly O: typeof ListChangesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

