//
// Copyright 2022 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.6.0 with parameter "target=js+dts,js_import_style=legacy_commonjs"
// @generated from file src/api/yorkie/v1/admin.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { proto3 } = require("@bufbuild/protobuf");
const { Change, DocumentSummary, Project, UpdatableProjectFields, User } = require("./resources_pb.js");

/**
 * @generated from message yorkie.v1.SignUpRequest
 */
const SignUpRequest = proto3.makeMessageType(
  "yorkie.v1.SignUpRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.SignUpResponse
 */
const SignUpResponse = proto3.makeMessageType(
  "yorkie.v1.SignUpResponse",
  () => [
    { no: 1, name: "user", kind: "message", T: User },
  ],
);

/**
 * @generated from message yorkie.v1.LogInRequest
 */
const LogInRequest = proto3.makeMessageType(
  "yorkie.v1.LogInRequest",
  () => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.LogInResponse
 */
const LogInResponse = proto3.makeMessageType(
  "yorkie.v1.LogInResponse",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.CreateProjectRequest
 */
const CreateProjectRequest = proto3.makeMessageType(
  "yorkie.v1.CreateProjectRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.CreateProjectResponse
 */
const CreateProjectResponse = proto3.makeMessageType(
  "yorkie.v1.CreateProjectResponse",
  () => [
    { no: 1, name: "project", kind: "message", T: Project },
  ],
);

/**
 * @generated from message yorkie.v1.GetProjectRequest
 */
const GetProjectRequest = proto3.makeMessageType(
  "yorkie.v1.GetProjectRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.GetProjectResponse
 */
const GetProjectResponse = proto3.makeMessageType(
  "yorkie.v1.GetProjectResponse",
  () => [
    { no: 1, name: "project", kind: "message", T: Project },
  ],
);

/**
 * @generated from message yorkie.v1.ListProjectsRequest
 */
const ListProjectsRequest = proto3.makeMessageType(
  "yorkie.v1.ListProjectsRequest",
  [],
);

/**
 * @generated from message yorkie.v1.ListProjectsResponse
 */
const ListProjectsResponse = proto3.makeMessageType(
  "yorkie.v1.ListProjectsResponse",
  () => [
    { no: 1, name: "projects", kind: "message", T: Project, repeated: true },
  ],
);

/**
 * @generated from message yorkie.v1.UpdateProjectRequest
 */
const UpdateProjectRequest = proto3.makeMessageType(
  "yorkie.v1.UpdateProjectRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "fields", kind: "message", T: UpdatableProjectFields },
  ],
);

/**
 * @generated from message yorkie.v1.UpdateProjectResponse
 */
const UpdateProjectResponse = proto3.makeMessageType(
  "yorkie.v1.UpdateProjectResponse",
  () => [
    { no: 1, name: "project", kind: "message", T: Project },
  ],
);

/**
 * @generated from message yorkie.v1.ListDocumentsRequest
 */
const ListDocumentsRequest = proto3.makeMessageType(
  "yorkie.v1.ListDocumentsRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "previous_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "is_forward", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "include_snapshot", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.ListDocumentsResponse
 */
const ListDocumentsResponse = proto3.makeMessageType(
  "yorkie.v1.ListDocumentsResponse",
  () => [
    { no: 1, name: "documents", kind: "message", T: DocumentSummary, repeated: true },
  ],
);

/**
 * @generated from message yorkie.v1.GetDocumentRequest
 */
const GetDocumentRequest = proto3.makeMessageType(
  "yorkie.v1.GetDocumentRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.GetDocumentResponse
 */
const GetDocumentResponse = proto3.makeMessageType(
  "yorkie.v1.GetDocumentResponse",
  () => [
    { no: 1, name: "document", kind: "message", T: DocumentSummary },
  ],
);

/**
 * @generated from message yorkie.v1.RemoveDocumentByAdminRequest
 */
const RemoveDocumentByAdminRequest = proto3.makeMessageType(
  "yorkie.v1.RemoveDocumentByAdminRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "force", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.RemoveDocumentByAdminResponse
 */
const RemoveDocumentByAdminResponse = proto3.makeMessageType(
  "yorkie.v1.RemoveDocumentByAdminResponse",
  [],
);

/**
 * @generated from message yorkie.v1.GetSnapshotMetaRequest
 */
const GetSnapshotMetaRequest = proto3.makeMessageType(
  "yorkie.v1.GetSnapshotMetaRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "server_seq", kind: "scalar", T: 3 /* ScalarType.INT64 */, L: 1 /* LongType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.GetSnapshotMetaResponse
 */
const GetSnapshotMetaResponse = proto3.makeMessageType(
  "yorkie.v1.GetSnapshotMetaResponse",
  () => [
    { no: 1, name: "snapshot", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "lamport", kind: "scalar", T: 3 /* ScalarType.INT64 */, L: 1 /* LongType.STRING */ },
  ],
);

/**
 * @generated from message yorkie.v1.SearchDocumentsRequest
 */
const SearchDocumentsRequest = proto3.makeMessageType(
  "yorkie.v1.SearchDocumentsRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message yorkie.v1.SearchDocumentsResponse
 */
const SearchDocumentsResponse = proto3.makeMessageType(
  "yorkie.v1.SearchDocumentsResponse",
  () => [
    { no: 1, name: "total_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "documents", kind: "message", T: DocumentSummary, repeated: true },
  ],
);

/**
 * @generated from message yorkie.v1.ListChangesRequest
 */
const ListChangesRequest = proto3.makeMessageType(
  "yorkie.v1.ListChangesRequest",
  () => [
    { no: 1, name: "project_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "document_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "previous_seq", kind: "scalar", T: 3 /* ScalarType.INT64 */, L: 1 /* LongType.STRING */ },
    { no: 4, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "is_forward", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message yorkie.v1.ListChangesResponse
 */
const ListChangesResponse = proto3.makeMessageType(
  "yorkie.v1.ListChangesResponse",
  () => [
    { no: 1, name: "changes", kind: "message", T: Change, repeated: true },
  ],
);


exports.SignUpRequest = SignUpRequest;
exports.SignUpResponse = SignUpResponse;
exports.LogInRequest = LogInRequest;
exports.LogInResponse = LogInResponse;
exports.CreateProjectRequest = CreateProjectRequest;
exports.CreateProjectResponse = CreateProjectResponse;
exports.GetProjectRequest = GetProjectRequest;
exports.GetProjectResponse = GetProjectResponse;
exports.ListProjectsRequest = ListProjectsRequest;
exports.ListProjectsResponse = ListProjectsResponse;
exports.UpdateProjectRequest = UpdateProjectRequest;
exports.UpdateProjectResponse = UpdateProjectResponse;
exports.ListDocumentsRequest = ListDocumentsRequest;
exports.ListDocumentsResponse = ListDocumentsResponse;
exports.GetDocumentRequest = GetDocumentRequest;
exports.GetDocumentResponse = GetDocumentResponse;
exports.RemoveDocumentByAdminRequest = RemoveDocumentByAdminRequest;
exports.RemoveDocumentByAdminResponse = RemoveDocumentByAdminResponse;
exports.GetSnapshotMetaRequest = GetSnapshotMetaRequest;
exports.GetSnapshotMetaResponse = GetSnapshotMetaResponse;
exports.SearchDocumentsRequest = SearchDocumentsRequest;
exports.SearchDocumentsResponse = SearchDocumentsResponse;
exports.ListChangesRequest = ListChangesRequest;
exports.ListChangesResponse = ListChangesResponse;
