//
// Copyright 2022 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file src/api/yorkie/v1/admin.proto (package yorkie.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChangePasswordRequest, ChangePasswordResponse, CreateDocumentRequest, CreateDocumentResponse, CreateProjectRequest, CreateProjectResponse, CreateSchemaRequest, CreateSchemaResponse, DeleteAccountRequest, DeleteAccountResponse, GetChannelsRequest, GetChannelsResponse, GetDocumentRequest, GetDocumentResponse, GetDocumentsRequest, GetDocumentsResponse, GetProjectRequest, GetProjectResponse, GetProjectStatsRequest, GetProjectStatsResponse, GetSchemaRequest, GetSchemaResponse, GetSchemasRequest, GetSchemasResponse, GetServerVersionRequest, GetServerVersionResponse, GetSnapshotMetaRequest, GetSnapshotMetaResponse, ListChangesRequest, ListChangesResponse, ListDocumentsRequest, ListDocumentsResponse, ListProjectsRequest, ListProjectsResponse, ListSchemasRequest, ListSchemasResponse, LogInRequest, LogInResponse, RemoveDocumentByAdminRequest, RemoveDocumentByAdminResponse, RemoveSchemaRequest, RemoveSchemaResponse, RotateProjectKeysRequest, RotateProjectKeysResponse, SearchDocumentsRequest, SearchDocumentsResponse, SignUpRequest, SignUpResponse, UpdateDocumentRequest, UpdateDocumentResponse, UpdateProjectRequest, UpdateProjectResponse } from "./admin_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Admin is a service that provides a API for Admin.
 *
 * @generated from service yorkie.v1.AdminService
 */
export const AdminService = {
  typeName: "yorkie.v1.AdminService",
  methods: {
    /**
     * @generated from rpc yorkie.v1.AdminService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: SignUpResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.LogIn
     */
    logIn: {
      name: "LogIn",
      I: LogInRequest,
      O: LogInResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.DeleteAccount
     */
    deleteAccount: {
      name: "DeleteAccount",
      I: DeleteAccountRequest,
      O: DeleteAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ChangePassword
     */
    changePassword: {
      name: "ChangePassword",
      I: ChangePasswordRequest,
      O: ChangePasswordResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: CreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListProjects
     */
    listProjects: {
      name: "ListProjects",
      I: ListProjectsRequest,
      O: ListProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetProject
     */
    getProject: {
      name: "GetProject",
      I: GetProjectRequest,
      O: GetProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetProjectStats
     */
    getProjectStats: {
      name: "GetProjectStats",
      I: GetProjectStatsRequest,
      O: GetProjectStatsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.UpdateProject
     */
    updateProject: {
      name: "UpdateProject",
      I: UpdateProjectRequest,
      O: UpdateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.CreateDocument
     */
    createDocument: {
      name: "CreateDocument",
      I: CreateDocumentRequest,
      O: CreateDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListDocuments
     */
    listDocuments: {
      name: "ListDocuments",
      I: ListDocumentsRequest,
      O: ListDocumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetDocument
     */
    getDocument: {
      name: "GetDocument",
      I: GetDocumentRequest,
      O: GetDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetDocuments
     */
    getDocuments: {
      name: "GetDocuments",
      I: GetDocumentsRequest,
      O: GetDocumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.UpdateDocument
     */
    updateDocument: {
      name: "UpdateDocument",
      I: UpdateDocumentRequest,
      O: UpdateDocumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.RemoveDocumentByAdmin
     */
    removeDocumentByAdmin: {
      name: "RemoveDocumentByAdmin",
      I: RemoveDocumentByAdminRequest,
      O: RemoveDocumentByAdminResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetSnapshotMeta
     */
    getSnapshotMeta: {
      name: "GetSnapshotMeta",
      I: GetSnapshotMetaRequest,
      O: GetSnapshotMetaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.SearchDocuments
     */
    searchDocuments: {
      name: "SearchDocuments",
      I: SearchDocumentsRequest,
      O: SearchDocumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetChannels
     */
    getChannels: {
      name: "GetChannels",
      I: GetChannelsRequest,
      O: GetChannelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListChanges
     */
    listChanges: {
      name: "ListChanges",
      I: ListChangesRequest,
      O: ListChangesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.CreateSchema
     */
    createSchema: {
      name: "CreateSchema",
      I: CreateSchemaRequest,
      O: CreateSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.ListSchemas
     */
    listSchemas: {
      name: "ListSchemas",
      I: ListSchemasRequest,
      O: ListSchemasResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetSchema
     */
    getSchema: {
      name: "GetSchema",
      I: GetSchemaRequest,
      O: GetSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetSchemas
     */
    getSchemas: {
      name: "GetSchemas",
      I: GetSchemasRequest,
      O: GetSchemasResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.RemoveSchema
     */
    removeSchema: {
      name: "RemoveSchema",
      I: RemoveSchemaRequest,
      O: RemoveSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.GetServerVersion
     */
    getServerVersion: {
      name: "GetServerVersion",
      I: GetServerVersionRequest,
      O: GetServerVersionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc yorkie.v1.AdminService.RotateProjectKeys
     */
    rotateProjectKeys: {
      name: "RotateProjectKeys",
      I: RotateProjectKeysRequest,
      O: RotateProjectKeysResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

